<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Carbon;
use Hash;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Thêm mới dữ liệu vào cate
        DB::table('categories')->insert([
            [
                'id'   => 1,
                'name' => json_encode([
                    'vi' => 'Bữa sáng',
                    'en' => 'Breakfast'
                ]),
                'slug' => 'breakfast',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 2,
                'name' => json_encode([
                    'vi' => 'Bữa trưa',
                    'en' => 'Lunch'
                ]),
                'slug' => 'lunch',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 3,
                'name' => json_encode([
                    'vi' => 'Bữa tối',
                    'en' => 'Dinner'
                ]),
                'slug' => 'dinner',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 4,
                'name' => json_encode([
                    'vi' => 'Đồ uống',
                    'en' => 'Beverages'
                ]),
                'slug' => 'beverages',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            ]);
        // Thêm mới dữ liệu vào menu
        DB::table('menus')->insert([
            // Bữa sáng
            [
                'name' => json_encode(['vi' => 'Bánh mì trứng', 'en' => 'Egg bread']),
                'slug' => 'egg-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm trứng ốp la.', 'en' => 'Bread with sunny-side-up egg.']),
                'price' => 20000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh cuốn', 'en' => 'Rolled rice pancake']),
                'slug' => 'rolled-rice-pancake',
                'description' => json_encode(['vi' => 'Bánh cuốn chả giò nóng hổi.', 'en' => 'Hot rolled rice pancake with pork.']),
                'price' => 30000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Xôi mặn', 'en' => 'Savory sticky rice']),
                'slug' => 'savory-sticky-rice',
                'description' => json_encode(['vi' => 'Xôi mặn với thịt và chà bông.', 'en' => 'Sticky rice with meat and floss.']),
                'price' => 25000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo thịt bằm', 'en' => 'Minced pork porridge']),
                'slug' => 'minced-pork-porridge',
                'description' => json_encode(['vi' => 'Cháo thịt bằm thơm ngon.', 'en' => 'Delicious minced pork porridge.']),
                'price' => 35000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Phở gà', 'en' => 'Chicken noodle soup']),
                'slug' => 'chicken-noodle-soup',
                'description' => json_encode(['vi' => 'Phở gà thơm ngon.', 'en' => 'Delicious chicken noodle soup.']),
                'price' => 40000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún thịt nướng', 'en' => 'Grilled pork vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún thịt nướng với rau sống.', 'en' => 'Vermicelli with grilled pork and fresh veggies.']),
                'price' => 45000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh ướt', 'en' => 'Wet rice paper']),
                'slug' => 'wet-rice-paper',
                'description' => json_encode(['vi' => 'Bánh ướt với chả và hành phi.', 'en' => 'Wet rice paper with sausage and fried onions.']),
                'price' => 28000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Miến gà', 'en' => 'Chicken vermicelli']),
                'slug' => 'chicken-vermicelli',
                'description' => json_encode(['vi' => 'Miến gà thơm ngon.', 'en' => 'Tasty chicken vermicelli.']),
                'price' => 38000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo lòng', 'en' => 'Pork intestine porridge']),
                'slug' => 'pork-intestine-porridge',
                'description' => json_encode(['vi' => 'Cháo lòng ngon miệng.', 'en' => 'Delicious pork intestine porridge.']),
                'price' => 32000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì chả cá', 'en' => 'Fish cake bread']),
                'slug' => 'fish-cake-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm chả cá.', 'en' => 'Bread with fish cake.']),
                'price' => 22000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa trưa
            [
                'name' => json_encode(['vi' => 'Cơm tấm sườn', 'en' => 'Broken rice with pork chop']),
                'slug' => 'broken-rice-pork-chop',
                'description' => json_encode(['vi' => 'Cơm tấm ăn kèm sườn nướng.', 'en' => 'Broken rice served with grilled pork chop.']),
                'price' => 55000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà ri gà', 'en' => 'Chicken curry']),
                'slug' => 'chicken-curry',
                'description' => json_encode(['vi' => 'Cà ri gà với cơm trắng.', 'en' => 'Chicken curry served with white rice.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm chiên Dương Châu', 'en' => 'Yangzhou fried rice']),
                'slug' => 'yangzhou-fried-rice',
                'description' => json_encode(['vi' => 'Cơm chiên với tôm và thịt.', 'en' => 'Fried rice with shrimp and meat.']),
                'price' => 45000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún bò Huế', 'en' => 'Hue beef noodle soup']),
                'slug' => 'hue-beef-noodle-soup',
                'description' => json_encode(['vi' => 'Bún bò với nước dùng đậm đà.', 'en' => 'Beef noodle soup with rich broth.']),
                'price' => 50000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì xào hải sản', 'en' => 'Stir-fried noodles with seafood']),
                'slug' => 'stir-fried-noodles-seafood',
                'description' => json_encode(['vi' => 'Mì xào với hải sản tươi ngon.', 'en' => 'Stir-fried noodles with fresh seafood.']),
                'price' => 70000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà kho gừng', 'en' => 'Ginger chicken']),
                'slug' => 'ginger-chicken',
                'description' => json_encode(['vi' => 'Gà kho với gừng và hành.', 'en' => 'Chicken stewed with ginger and onion.']),
                'price' => 52000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò lúc lắc', 'en' => 'Shaking beef']),
                'slug' => 'shaking-beef',
                'description' => json_encode(['vi' => 'Bò xào với rau củ.', 'en' => 'Beef stir-fried with vegetables.']),
                'price' => 75000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá kho tộ', 'en' => 'Braised fish']),
                'slug' => 'braised-fish',
                'description' => json_encode(['vi' => 'Cá kho với nước mắm đậm đà.', 'en' => 'Braised fish with rich fish sauce.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún chả', 'en' => 'Grilled pork with vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún chả với thịt nướng và nước chấm.', 'en' => 'Vermicelli with grilled pork and dipping sauce.']),
                'price' => 58000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm bò nướng', 'en' => 'Grilled beef rice']),
                'slug' => 'grilled-beef-rice',
                'description' => json_encode(['vi' => 'Cơm ăn kèm với bò nướng.', 'en' => 'Rice served with grilled beef.']),
                'price' => 63000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa tối
            [
                'name' => json_encode(['vi' => 'Thịt kho tàu', 'en' => 'Braised pork with eggs']),
                'slug' => 'braised-pork-eggs',
                'description' => json_encode(['vi' => 'Thịt heo kho với trứng và nước dừa.', 'en' => 'Pork braised with eggs and coconut water.']),
                'price' => 70000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Lẩu cá', 'en' => 'Fish hotpot']),
                'slug' => 'fish-hotpot',
                'description' => json_encode(['vi' => 'Lẩu cá với nhiều loại rau.', 'en' => 'Fish hotpot with various vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà nướng mật ong', 'en' => 'Honey glazed chicken']),
                'slug' => 'honey-glazed-chicken',
                'description' => json_encode(['vi' => 'Gà nướng với sốt mật ong.', 'en' => 'Grilled chicken with honey sauce.']),
                'price' => 80000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá nướng muối ớt', 'en' => 'Grilled fish with chili salt']),
                'slug' => 'grilled-fish-chili-salt',
                'description' => json_encode(['vi' => 'Cá nướng với gia vị muối ớt.', 'en' => 'Grilled fish with chili salt seasoning.']),
                'price' => 65000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò kho', 'en' => 'Beef stew']),
                'slug' => 'beef-stew',
                'description' => json_encode(['vi' => 'Bò kho với cà rốt và khoai tây.', 'en' => 'Beef stew with carrots and potatoes.']),
                'price' => 75000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Đậu hũ sốt cà chua', 'en' => 'Tofu in tomato sauce']),
                'slug' => 'tofu-tomato-sauce',
                'description' => json_encode(['vi' => 'Đậu hũ sốt cà chua với cơm.', 'en' => 'Tofu in tomato sauce served with rice.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì Ý sốt bò', 'en' => 'Spaghetti with beef sauce']),
                'slug' => 'spaghetti-beef-sauce',
                'description' => json_encode(['vi' => 'Mì Ý sốt bò với phô mai.', 'en' => 'Spaghetti with beef sauce and cheese.']),
                'price' => 90000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Sườn nướng BBQ', 'en' => 'BBQ ribs']),
                'slug' => 'bbq-ribs',
                'description' => json_encode(['vi' => 'Sườn nướng với sốt BBQ.', 'en' => 'Ribs grilled with BBQ sauce.']),
                'price' => 95000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Salad trộn', 'en' => 'Mixed salad']),
                'slug' => 'mixed-salad',
                'description' => json_encode(['vi' => 'Salad với rau củ tươi ngon.', 'en' => 'Salad with fresh vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì kẹp thịt', 'en' => 'Banh mi sandwich']),
                'slug' => 'banh-mi-sandwich',
                'description' => json_encode(['vi' => 'Bánh mì với thịt nguội và rau.', 'en' => 'Sandwich with cold cuts and vegetables.']),
                'price' => 50000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Chả giò', 'en' => 'Spring rolls']),
                'slug' => 'spring-rolls',
                'description' => json_encode(['vi' => 'Chả giò chiên giòn ăn kèm nước mắm.', 'en' => 'Crispy spring rolls served with dipping sauce.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Đồ uống
            [
                'name' => json_encode(['vi' => 'Trà sữa', 'en' => 'Milk tea']),
                'slug' => 'milk-tea',
                'description' => json_encode(['vi' => 'Một ly trà sữa ngọt ngào.', 'en' => 'A sweet cup of milk tea.']),
                'price' => 35000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà phê sữa đá', 'en' => 'Iced coffee with milk']),
                'slug' => 'iced-coffee-milk',
                'description' => json_encode(['vi' => 'Một ly cà phê thơm ngon.', 'en' => 'A delicious cup of coffee.']),
                'price' => 40000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước cam', 'en' => 'Orange juice']),
                'slug' => 'orange-juice',
                'description' => json_encode(['vi' => 'Một ly nước cam tươi.', 'en' => 'A glass of fresh orange juice.']),
                'price' => 25000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước chanh', 'en' => 'Lemonade']),
                'slug' => 'lemonade',
                'description' => json_encode(['vi' => 'Một ly nước chanh mát.', 'en' => 'A cool glass of lemonade.']),
                'price' => 20000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước khoáng', 'en' => 'Mineral water']),
                'slug' => 'mineral-water',
                'description' => json_encode(['vi' => 'Nước khoáng tinh khiết.', 'en' => 'Pure mineral water.']),
                'price' => 10000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
        // Thêm mới dữ liệu vào menu
        DB::table('menus')->insert([
            // Bữa sáng
            [
                'name' => json_encode(['vi' => 'Bánh mì trứng', 'en' => 'Egg bread']),
                'slug' => 'egg-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm trứng ốp la.', 'en' => 'Bread with sunny-side-up egg.']),
                'price' => 20000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh cuốn', 'en' => 'Rolled rice pancake']),
                'slug' => 'rolled-rice-pancake',
                'description' => json_encode(['vi' => 'Bánh cuốn chả giò nóng hổi.', 'en' => 'Hot rolled rice pancake with pork.']),
                'price' => 30000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Xôi mặn', 'en' => 'Savory sticky rice']),
                'slug' => 'savory-sticky-rice',
                'description' => json_encode(['vi' => 'Xôi mặn với thịt và chà bông.', 'en' => 'Sticky rice with meat and floss.']),
                'price' => 25000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo thịt bằm', 'en' => 'Minced pork porridge']),
                'slug' => 'minced-pork-porridge',
                'description' => json_encode(['vi' => 'Cháo thịt bằm thơm ngon.', 'en' => 'Delicious minced pork porridge.']),
                'price' => 35000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Phở gà', 'en' => 'Chicken noodle soup']),
                'slug' => 'chicken-noodle-soup',
                'description' => json_encode(['vi' => 'Phở gà thơm ngon.', 'en' => 'Delicious chicken noodle soup.']),
                'price' => 40000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún thịt nướng', 'en' => 'Grilled pork vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún thịt nướng với rau sống.', 'en' => 'Vermicelli with grilled pork and fresh veggies.']),
                'price' => 45000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh ướt', 'en' => 'Wet rice paper']),
                'slug' => 'wet-rice-paper',
                'description' => json_encode(['vi' => 'Bánh ướt với chả và hành phi.', 'en' => 'Wet rice paper with sausage and fried onions.']),
                'price' => 28000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Miến gà', 'en' => 'Chicken vermicelli']),
                'slug' => 'chicken-vermicelli',
                'description' => json_encode(['vi' => 'Miến gà thơm ngon.', 'en' => 'Tasty chicken vermicelli.']),
                'price' => 38000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo lòng', 'en' => 'Pork intestine porridge']),
                'slug' => 'pork-intestine-porridge',
                'description' => json_encode(['vi' => 'Cháo lòng ngon miệng.', 'en' => 'Delicious pork intestine porridge.']),
                'price' => 32000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì chả cá', 'en' => 'Fish cake bread']),
                'slug' => 'fish-cake-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm chả cá.', 'en' => 'Bread with fish cake.']),
                'price' => 22000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa trưa
            [
                'name' => json_encode(['vi' => 'Cơm tấm sườn', 'en' => 'Broken rice with pork chop']),
                'slug' => 'broken-rice-pork-chop',
                'description' => json_encode(['vi' => 'Cơm tấm ăn kèm sườn nướng.', 'en' => 'Broken rice served with grilled pork chop.']),
                'price' => 55000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà ri gà', 'en' => 'Chicken curry']),
                'slug' => 'chicken-curry',
                'description' => json_encode(['vi' => 'Cà ri gà với cơm trắng.', 'en' => 'Chicken curry served with white rice.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm chiên Dương Châu', 'en' => 'Yangzhou fried rice']),
                'slug' => 'yangzhou-fried-rice',
                'description' => json_encode(['vi' => 'Cơm chiên với tôm và thịt.', 'en' => 'Fried rice with shrimp and meat.']),
                'price' => 45000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún bò Huế', 'en' => 'Hue beef noodle soup']),
                'slug' => 'hue-beef-noodle-soup',
                'description' => json_encode(['vi' => 'Bún bò với nước dùng đậm đà.', 'en' => 'Beef noodle soup with rich broth.']),
                'price' => 50000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì xào hải sản', 'en' => 'Stir-fried noodles with seafood']),
                'slug' => 'stir-fried-noodles-seafood',
                'description' => json_encode(['vi' => 'Mì xào với hải sản tươi ngon.', 'en' => 'Stir-fried noodles with fresh seafood.']),
                'price' => 70000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà kho gừng', 'en' => 'Ginger chicken']),
                'slug' => 'ginger-chicken',
                'description' => json_encode(['vi' => 'Gà kho với gừng và hành.', 'en' => 'Chicken stewed with ginger and onion.']),
                'price' => 52000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò lúc lắc', 'en' => 'Shaking beef']),
                'slug' => 'shaking-beef',
                'description' => json_encode(['vi' => 'Bò xào với rau củ.', 'en' => 'Beef stir-fried with vegetables.']),
                'price' => 75000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá kho tộ', 'en' => 'Braised fish']),
                'slug' => 'braised-fish',
                'description' => json_encode(['vi' => 'Cá kho với nước mắm đậm đà.', 'en' => 'Braised fish with rich fish sauce.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún chả', 'en' => 'Grilled pork with vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún chả với thịt nướng và nước chấm.', 'en' => 'Vermicelli with grilled pork and dipping sauce.']),
                'price' => 58000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm bò nướng', 'en' => 'Grilled beef rice']),
                'slug' => 'grilled-beef-rice',
                'description' => json_encode(['vi' => 'Cơm ăn kèm với bò nướng.', 'en' => 'Rice served with grilled beef.']),
                'price' => 63000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa tối
            [
                'name' => json_encode(['vi' => 'Thịt kho tàu', 'en' => 'Braised pork with eggs']),
                'slug' => 'braised-pork-eggs',
                'description' => json_encode(['vi' => 'Thịt heo kho với trứng và nước dừa.', 'en' => 'Pork braised with eggs and coconut water.']),
                'price' => 70000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Lẩu cá', 'en' => 'Fish hotpot']),
                'slug' => 'fish-hotpot',
                'description' => json_encode(['vi' => 'Lẩu cá với nhiều loại rau.', 'en' => 'Fish hotpot with various vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà nướng mật ong', 'en' => 'Honey glazed chicken']),
                'slug' => 'honey-glazed-chicken',
                'description' => json_encode(['vi' => 'Gà nướng với sốt mật ong.', 'en' => 'Grilled chicken with honey sauce.']),
                'price' => 80000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá nướng muối ớt', 'en' => 'Grilled fish with chili salt']),
                'slug' => 'grilled-fish-chili-salt',
                'description' => json_encode(['vi' => 'Cá nướng với gia vị muối ớt.', 'en' => 'Grilled fish with chili salt seasoning.']),
                'price' => 65000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò kho', 'en' => 'Beef stew']),
                'slug' => 'beef-stew',
                'description' => json_encode(['vi' => 'Bò kho với cà rốt và khoai tây.', 'en' => 'Beef stew with carrots and potatoes.']),
                'price' => 75000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Đậu hũ sốt cà chua', 'en' => 'Tofu in tomato sauce']),
                'slug' => 'tofu-tomato-sauce',
                'description' => json_encode(['vi' => 'Đậu hũ sốt cà chua với cơm.', 'en' => 'Tofu in tomato sauce served with rice.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì Ý sốt bò', 'en' => 'Spaghetti with beef sauce']),
                'slug' => 'spaghetti-beef-sauce',
                'description' => json_encode(['vi' => 'Mì Ý sốt bò với phô mai.', 'en' => 'Spaghetti with beef sauce and cheese.']),
                'price' => 90000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Sườn nướng BBQ', 'en' => 'BBQ ribs']),
                'slug' => 'bbq-ribs',
                'description' => json_encode(['vi' => 'Sườn nướng với sốt BBQ.', 'en' => 'Ribs grilled with BBQ sauce.']),
                'price' => 95000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Salad trộn', 'en' => 'Mixed salad']),
                'slug' => 'mixed-salad',
                'description' => json_encode(['vi' => 'Salad với rau củ tươi ngon.', 'en' => 'Salad with fresh vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì kẹp thịt', 'en' => 'Banh mi sandwich']),
                'slug' => 'banh-mi-sandwich',
                'description' => json_encode(['vi' => 'Bánh mì với thịt nguội và rau.', 'en' => 'Sandwich with cold cuts and vegetables.']),
                'price' => 50000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Chả giò', 'en' => 'Spring rolls']),
                'slug' => 'spring-rolls',
                'description' => json_encode(['vi' => 'Chả giò chiên giòn ăn kèm nước mắm.', 'en' => 'Crispy spring rolls served with dipping sauce.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Đồ uống
            [
                'name' => json_encode(['vi' => 'Trà sữa', 'en' => 'Milk tea']),
                'slug' => 'milk-tea',
                'description' => json_encode(['vi' => 'Một ly trà sữa ngọt ngào.', 'en' => 'A sweet cup of milk tea.']),
                'price' => 35000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà phê sữa đá', 'en' => 'Iced coffee with milk']),
                'slug' => 'iced-coffee-milk',
                'description' => json_encode(['vi' => 'Một ly cà phê thơm ngon.', 'en' => 'A delicious cup of coffee.']),
                'price' => 40000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước cam', 'en' => 'Orange juice']),
                'slug' => 'orange-juice',
                'description' => json_encode(['vi' => 'Một ly nước cam tươi.', 'en' => 'A glass of fresh orange juice.']),
                'price' => 25000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước chanh', 'en' => 'Lemonade']),
                'slug' => 'lemonade',
                'description' => json_encode(['vi' => 'Một ly nước chanh mát.', 'en' => 'A cool glass of lemonade.']),
                'price' => 20000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước khoáng', 'en' => 'Mineral water']),
                'slug' => 'mineral-water',
                'description' => json_encode(['vi' => 'Nước khoáng tinh khiết.', 'en' => 'Pure mineral water.']),
                'price' => 10000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
        // Thêm mới dữ liệu vào menu
        DB::table('menus')->insert([
            // Bữa sáng
            [
                'name' => json_encode(['vi' => 'Bánh mì trứng', 'en' => 'Egg bread']),
                'slug' => 'egg-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm trứng ốp la.', 'en' => 'Bread with sunny-side-up egg.']),
                'price' => 20000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh cuốn', 'en' => 'Rolled rice pancake']),
                'slug' => 'rolled-rice-pancake',
                'description' => json_encode(['vi' => 'Bánh cuốn chả giò nóng hổi.', 'en' => 'Hot rolled rice pancake with pork.']),
                'price' => 30000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Xôi mặn', 'en' => 'Savory sticky rice']),
                'slug' => 'savory-sticky-rice',
                'description' => json_encode(['vi' => 'Xôi mặn với thịt và chà bông.', 'en' => 'Sticky rice with meat and floss.']),
                'price' => 25000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo thịt bằm', 'en' => 'Minced pork porridge']),
                'slug' => 'minced-pork-porridge',
                'description' => json_encode(['vi' => 'Cháo thịt bằm thơm ngon.', 'en' => 'Delicious minced pork porridge.']),
                'price' => 35000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Phở gà', 'en' => 'Chicken noodle soup']),
                'slug' => 'chicken-noodle-soup',
                'description' => json_encode(['vi' => 'Phở gà thơm ngon.', 'en' => 'Delicious chicken noodle soup.']),
                'price' => 40000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún thịt nướng', 'en' => 'Grilled pork vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún thịt nướng với rau sống.', 'en' => 'Vermicelli with grilled pork and fresh veggies.']),
                'price' => 45000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh ướt', 'en' => 'Wet rice paper']),
                'slug' => 'wet-rice-paper',
                'description' => json_encode(['vi' => 'Bánh ướt với chả và hành phi.', 'en' => 'Wet rice paper with sausage and fried onions.']),
                'price' => 28000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Miến gà', 'en' => 'Chicken vermicelli']),
                'slug' => 'chicken-vermicelli',
                'description' => json_encode(['vi' => 'Miến gà thơm ngon.', 'en' => 'Tasty chicken vermicelli.']),
                'price' => 38000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cháo lòng', 'en' => 'Pork intestine porridge']),
                'slug' => 'pork-intestine-porridge',
                'description' => json_encode(['vi' => 'Cháo lòng ngon miệng.', 'en' => 'Delicious pork intestine porridge.']),
                'price' => 32000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì chả cá', 'en' => 'Fish cake bread']),
                'slug' => 'fish-cake-bread',
                'description' => json_encode(['vi' => 'Bánh mì kèm chả cá.', 'en' => 'Bread with fish cake.']),
                'price' => 22000,
                'category_id' => '1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa trưa
            [
                'name' => json_encode(['vi' => 'Cơm tấm sườn', 'en' => 'Broken rice with pork chop']),
                'slug' => 'broken-rice-pork-chop',
                'description' => json_encode(['vi' => 'Cơm tấm ăn kèm sườn nướng.', 'en' => 'Broken rice served with grilled pork chop.']),
                'price' => 55000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà ri gà', 'en' => 'Chicken curry']),
                'slug' => 'chicken-curry',
                'description' => json_encode(['vi' => 'Cà ri gà với cơm trắng.', 'en' => 'Chicken curry served with white rice.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm chiên Dương Châu', 'en' => 'Yangzhou fried rice']),
                'slug' => 'yangzhou-fried-rice',
                'description' => json_encode(['vi' => 'Cơm chiên với tôm và thịt.', 'en' => 'Fried rice with shrimp and meat.']),
                'price' => 45000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún bò Huế', 'en' => 'Hue beef noodle soup']),
                'slug' => 'hue-beef-noodle-soup',
                'description' => json_encode(['vi' => 'Bún bò với nước dùng đậm đà.', 'en' => 'Beef noodle soup with rich broth.']),
                'price' => 50000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì xào hải sản', 'en' => 'Stir-fried noodles with seafood']),
                'slug' => 'stir-fried-noodles-seafood',
                'description' => json_encode(['vi' => 'Mì xào với hải sản tươi ngon.', 'en' => 'Stir-fried noodles with fresh seafood.']),
                'price' => 70000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà kho gừng', 'en' => 'Ginger chicken']),
                'slug' => 'ginger-chicken',
                'description' => json_encode(['vi' => 'Gà kho với gừng và hành.', 'en' => 'Chicken stewed with ginger and onion.']),
                'price' => 52000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò lúc lắc', 'en' => 'Shaking beef']),
                'slug' => 'shaking-beef',
                'description' => json_encode(['vi' => 'Bò xào với rau củ.', 'en' => 'Beef stir-fried with vegetables.']),
                'price' => 75000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá kho tộ', 'en' => 'Braised fish']),
                'slug' => 'braised-fish',
                'description' => json_encode(['vi' => 'Cá kho với nước mắm đậm đà.', 'en' => 'Braised fish with rich fish sauce.']),
                'price' => 60000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bún chả', 'en' => 'Grilled pork with vermicelli']),
                'slug' => 'grilled-pork-vermicelli',
                'description' => json_encode(['vi' => 'Bún chả với thịt nướng và nước chấm.', 'en' => 'Vermicelli with grilled pork and dipping sauce.']),
                'price' => 58000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cơm bò nướng', 'en' => 'Grilled beef rice']),
                'slug' => 'grilled-beef-rice',
                'description' => json_encode(['vi' => 'Cơm ăn kèm với bò nướng.', 'en' => 'Rice served with grilled beef.']),
                'price' => 63000,
                'category_id' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa tối
            [
                'name' => json_encode(['vi' => 'Thịt kho tàu', 'en' => 'Braised pork with eggs']),
                'slug' => 'braised-pork-eggs',
                'description' => json_encode(['vi' => 'Thịt heo kho với trứng và nước dừa.', 'en' => 'Pork braised with eggs and coconut water.']),
                'price' => 70000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Lẩu cá', 'en' => 'Fish hotpot']),
                'slug' => 'fish-hotpot',
                'description' => json_encode(['vi' => 'Lẩu cá với nhiều loại rau.', 'en' => 'Fish hotpot with various vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Gà nướng mật ong', 'en' => 'Honey glazed chicken']),
                'slug' => 'honey-glazed-chicken',
                'description' => json_encode(['vi' => 'Gà nướng với sốt mật ong.', 'en' => 'Grilled chicken with honey sauce.']),
                'price' => 80000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cá nướng muối ớt', 'en' => 'Grilled fish with chili salt']),
                'slug' => 'grilled-fish-chili-salt',
                'description' => json_encode(['vi' => 'Cá nướng với gia vị muối ớt.', 'en' => 'Grilled fish with chili salt seasoning.']),
                'price' => 65000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bò kho', 'en' => 'Beef stew']),
                'slug' => 'beef-stew',
                'description' => json_encode(['vi' => 'Bò kho với cà rốt và khoai tây.', 'en' => 'Beef stew with carrots and potatoes.']),
                'price' => 75000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Đậu hũ sốt cà chua', 'en' => 'Tofu in tomato sauce']),
                'slug' => 'tofu-tomato-sauce',
                'description' => json_encode(['vi' => 'Đậu hũ sốt cà chua với cơm.', 'en' => 'Tofu in tomato sauce served with rice.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Mì Ý sốt bò', 'en' => 'Spaghetti with beef sauce']),
                'slug' => 'spaghetti-beef-sauce',
                'description' => json_encode(['vi' => 'Mì Ý sốt bò với phô mai.', 'en' => 'Spaghetti with beef sauce and cheese.']),
                'price' => 90000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Sườn nướng BBQ', 'en' => 'BBQ ribs']),
                'slug' => 'bbq-ribs',
                'description' => json_encode(['vi' => 'Sườn nướng với sốt BBQ.', 'en' => 'Ribs grilled with BBQ sauce.']),
                'price' => 95000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Salad trộn', 'en' => 'Mixed salad']),
                'slug' => 'mixed-salad',
                'description' => json_encode(['vi' => 'Salad với rau củ tươi ngon.', 'en' => 'Salad with fresh vegetables.']),
                'price' => 30000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Bánh mì kẹp thịt', 'en' => 'Banh mi sandwich']),
                'slug' => 'banh-mi-sandwich',
                'description' => json_encode(['vi' => 'Bánh mì với thịt nguội và rau.', 'en' => 'Sandwich with cold cuts and vegetables.']),
                'price' => 50000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Chả giò', 'en' => 'Spring rolls']),
                'slug' => 'spring-rolls',
                'description' => json_encode(['vi' => 'Chả giò chiên giòn ăn kèm nước mắm.', 'en' => 'Crispy spring rolls served with dipping sauce.']),
                'price' => 40000,
                'category_id' => '3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Đồ uống
            [
                'name' => json_encode(['vi' => 'Trà sữa', 'en' => 'Milk tea']),
                'slug' => 'milk-tea',
                'description' => json_encode(['vi' => 'Một ly trà sữa ngọt ngào.', 'en' => 'A sweet cup of milk tea.']),
                'price' => 35000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Cà phê sữa đá', 'en' => 'Iced coffee with milk']),
                'slug' => 'iced-coffee-milk',
                'description' => json_encode(['vi' => 'Một ly cà phê thơm ngon.', 'en' => 'A delicious cup of coffee.']),
                'price' => 40000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước cam', 'en' => 'Orange juice']),
                'slug' => 'orange-juice',
                'description' => json_encode(['vi' => 'Một ly nước cam tươi.', 'en' => 'A glass of fresh orange juice.']),
                'price' => 25000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước chanh', 'en' => 'Lemonade']),
                'slug' => 'lemonade',
                'description' => json_encode(['vi' => 'Một ly nước chanh mát.', 'en' => 'A cool glass of lemonade.']),
                'price' => 20000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => json_encode(['vi' => 'Nước khoáng', 'en' => 'Mineral water']),
                'slug' => 'mineral-water',
                'description' => json_encode(['vi' => 'Nước khoáng tinh khiết.', 'en' => 'Pure mineral water.']),
                'price' => 10000,
                'category_id' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
