<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Carbon;
use Hash;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{

    
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Thêm mới dữ liệu vào cate
        DB::table('categories')->insert([
            [
                'id'   => 1,
                'name' => 'Bữa sáng',
                'slug' => 'bua-sang',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 2,
                'name' => 'Bữa trưa',
                'slug' => 'bua-trua',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 3,
                'name' => 'Bữa tối',
                'slug' => 'bua-toi',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'   => 4,
                'name' => 'Đồ uống',
                'slug' => 'do-uong',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // [
            //     'name' => 'Chưa phân loại',
            //     'slug' => 'chua-phan-loai',
            //     'status' => 'active',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            ]);
        // Thêm mới dữ liệu vào menu
        DB::table('menus')->insert([
            // Bữa sáng
            [
                'name' => 'Bánh mì trứng',
                'slug' => 'egg-bread',
                'description' => 'Bánh mì kèm trứng ốp la.',
                'price' => 20000,
                'category_id' => '1',
                'image_url' => 'menu_files/banhmikeptrungopla.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bánh cuốn',
                'slug' => 'rolled-rice-pancake',
                'description' => 'Bánh cuốn chả giò nóng hổi.',
                'price' => 30000,
                'category_id' => '1',
                'image_url' => 'menu_files/banhcuon.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Xôi mặn',
                'slug' => 'savory-sticky-rice',
                'description' => 'Xôi mặn với thịt và chà bông.',
                'price' => 25000,
                'category_id' => '1',
                'image_url' => 'menu_files/xoiman.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cháo thịt bằm',
                'slug' => 'minced-pork-porridge',
                'description' => 'Cháo thịt bằm thơm ngon.',
                'price' => 35000,
                'category_id' => '1',
                'image_url' => 'menu_files/chaothitbam.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Phở gà',
                'slug' => 'chicken-noodle-soup',
                'description' => 'Phở gà thơm ngon.',
                'price' => 40000,
                'category_id' => '1',
                'image_url' => 'menu_files/phoga.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bún thịt nướng',
                'slug' => 'grilled-pork-vermicelli',
                'description' => 'Bún thịt nướng với rau sống.',
                'price' => 45000,
                'category_id' => '1',
                'image_url' => 'menu_files/bunthitnuong.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bánh ướt',
                'slug' => 'wet-rice-paper',
                'description' => 'Bánh ướt với chả và hành phi.',
                'price' => 28000,
                'category_id' => '1',
                'image_url' => 'menu_files/1.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Miến gà',
                'slug' => 'chicken-vermicelli',
                'description' => 'Miến gà thơm ngon.',
                'price' => 38000,
                'category_id' => '1',
                'image_url' => 'menu_files/2.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cháo lòng',
                'slug' => 'pork-intestine-porridge',
                'description' => 'Cháo lòng ngon miệng.',
                'price' => 32000,
                'category_id' => '1',
                'image_url' => 'menu_files/3.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bánh mì chả cá',
                'slug' => 'fish-cake-bread',
                'description' => 'Bánh mì kèm chả cá.',
                'price' => 22000,
                'category_id' => '1',
                'image_url' => 'menu_files/4.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa trưa
            [
                'name' => 'Cơm tấm sườn',
                'slug' => 'broken-rice-pork-chop',
                'description' => 'Cơm tấm ăn kèm sườn nướng.',
                'price' => 55000,
                'category_id' => '2',
                'image_url' => 'menu_files/5.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cà ri gà',
                'slug' => 'chicken-curry',
                'description' => 'Cà ri gà với cơm trắng.',
                'price' => 60000,
                'category_id' => '2',
                'image_url' => 'menu_files/6.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cơm chiên Dương Châu',
                'slug' => 'yangzhou-fried-rice',
                'description' => 'Cơm chiên với tôm và thịt.',
                'price' => 45000,
                'category_id' => '2',
                'image_url' => 'menu_files/7.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bún bò Huế',
                'slug' => 'hue-beef-noodle-soup',
                'description' => 'Bún bò với nước dùng đậm đà.',
                'price' => 50000,
                'category_id' => '2',
                'image_url' => 'menu_files/8.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mì xào hải sản',
                'slug' => 'stir-fried-noodles-seafood',
                'description' => 'Mì xào với hải sản tươi ngon.',
                'price' => 70000,
                'category_id' => '2',
                'image_url' => 'menu_files/9.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gà kho gừng',
                'slug' => 'ginger-chicken',
                'description' => 'Gà kho với gừng và hành.',
                'price' => 52000,
                'category_id' => '2',
                'image_url' => 'menu_files/10.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bò lúc lắc',
                'slug' => 'shaking-beef',
                'description' => 'Bò xào với rau củ.',
                'price' => 75000,
                'category_id' => '2',
                'image_url' => 'menu_files/11.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cá kho tộ',
                'slug' => 'braised-fish',
                'description' => 'Cá kho với nước mắm đậm đà.',
                'price' => 60000,
                'category_id' => '2',
                'image_url' => 'menu_files/12.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bún chả',
                'slug' => 'grilled-pork-vermicelli',
                'description' => 'Bún chả với thịt nướng và nước chấm.',
                'price' => 58000,
                'category_id' => '2',
                'image_url' => 'menu_files/13.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cơm bò nướng',
                'slug' => 'grilled-beef-rice',
                'description' => 'Cơm ăn kèm với bò nướng.',
                'price' => 63000,
                'category_id' => '2',
                'image_url' => 'menu_files/14.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Bữa tối
            [
                'name' => 'Thịt kho tàu',
                'slug' => 'braised-pork-eggs',
                'description' => 'Thịt heo kho với trứng và nước dừa.',
                'price' => 70000,
                'category_id' => '3',
                'image_url' => 'menu_files/15.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lẩu cá',
                'slug' => 'fish-hotpot',
                'description' => 'Lẩu cá với nhiều loại rau.',
                'price' => 30000,
                'category_id' => '3',
                'image_url' => 'menu_files/lauca.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gà nướng mật ong',
                'slug' => 'honey-glazed-chicken',
                'description' => 'Gà nướng với sốt mật ong.',
                'price' => 80000,
                'category_id' => '3',
                'image_url' => 'menu_files/1.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cá nướng muối ớt',
                'slug' => 'grilled-fish-chili-salt',
                'description' => 'Cá nướng với gia vị muối ớt.',
                'price' => 65000,
                'category_id' => '3',
                'image_url' => 'menu_files/2.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bò kho',
                'slug' => 'beef-stew',
                'description' => 'Bò kho với cà rốt và khoai tây.',
                'price' => 75000,
                'category_id' => '3',
                'image_url' => 'menu_files/3.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Đậu hũ sốt cà chua',
                'slug' => 'tofu-tomato-sauce',
                'description' => 'Đậu hũ sốt cà chua với cơm.',
                'price' => 40000,
                'category_id' => '3',
                'image_url' => 'menu_files/4.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mì Ý sốt bò',
                'slug' => 'spaghetti-beef-sauce',
                'description' => 'Mì Ý sốt bò với phô mai.',
                'price' => 90000,
                'category_id' => '3',
                'image_url' => 'menu_files/5.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sườn nướng BBQ',
                'slug' => 'bbq-ribs',
                'description' => 'Sườn nướng với sốt BBQ.',
                'price' => 95000,
                'category_id' => '3',
                'image_url' => 'menu_files/6.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Salad trộn',
                'slug' => 'mixed-salad',
                'description' => 'Salad với rau củ tươi ngon.',
                'price' => 30000,
                'category_id' => '3',
                'image_url' => 'menu_files/7.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bánh mì kẹp thịt',
                'slug' => 'banh-mi-sandwich',
                'description' => 'Bánh mì với thịt nguội và rau.',
                'price' => 50000,
                'category_id' => '3',
                'image_url' => 'menu_files/8.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chả giò',
                'slug' => 'spring-rolls',
                'description' => 'Chả giò chiên giòn ăn kèm nước mắm.',
                'price' => 40000,
                'category_id' => '3',
                'image_url' => 'menu_files/9.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Đồ uống
            [
                'name' => 'Trà sữa',
                'slug' => 'milk-tea',
                'description' => 'Một ly trà sữa ngọt ngào.',
                'price' => 35000,
                'category_id' => '4',
                'image_url' => 'menu_files/trasua.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cà phê sữa đá',
                'slug' => 'iced-coffee-milk',
                'description' => 'Một ly cà phê thơm ngon.',
                'price' => 40000,
                'category_id' => '4',
                'image_url' => 'menu_files/caphesuada.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nước cam',
                'slug' => 'orange-juice',
                'description' => 'Một ly nước cam tươi.',
                'price' => 25000,
                'category_id' => '4',
                'image_url' => 'menu_files/nuoccam.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nước chanh',
                'slug' => 'lemonade',
                'description' => 'Một ly nước chanh mát.',
                'price' => 20000,
                'category_id' => '4',
                'image_url' => 'menu_files/nuocchanh.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nước khoáng',
                'slug' => 'mineral-water',
                'description' => 'Nước khoáng tinh khiết.',
                'price' => 10000,
                'category_id' => '4',
                'image_url' => 'menu_files/nuockhoang.jpg',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
